# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frontend-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for frontend-iOS
      pod 'Alamofire'
      pod 'SwiftyJSON'
      pod 'CodableAlamofire'
  target 'frontend-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'frontend-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
